const BOOKING_STATUS_OPTIONS = [
  'CONFIRMED',
  'DEPOSIT_PAID',
  'PAID_IN_FULL',
  'WAITLISTED',
  'CHECKED_IN'
]

const OPERATIONAL_ROLE_OPTIONS = [
  'turnaround-manager',
  'housekeeping-lead',
  'guest-services-lead',
  'food-beverage-lead',
  'engineering-lead'
]

const TURNAROUND_OPERATION_STATUS_OPTIONS = [
  'PLANNED',
  'IN_PROGRESS',
  'READY',
  'WATCH',
  'BLOCKED',
  'COMPLETE'
]

const TURNAROUND_TASK_STATUS_OPTIONS = [
  'READY',
  'IN_PROGRESS',
  'BLOCKED',
  'WATCH',
  'COMPLETE'
]

const TURNAROUND_DEPENDENCY_STATUS_OPTIONS = [
  'ACTIVE',
  'CLEARED'
]

const TURNAROUND_HANDOFF_STATUS_OPTIONS = [
  'PENDING',
  'READY',
  'IN_REVIEW',
  'BLOCKED',
  'COMPLETE'
]

const TURNAROUND_ESCALATION_SEVERITY_OPTIONS = [
  'WATCH',
  'HIGH',
  'CRITICAL'
]

const TURNAROUND_ESCALATION_STATUS_OPTIONS = [
  'OPEN',
  'MONITORING',
  'RESOLVED'
]

const TURNAROUND_SIGNOFF_STATUS_OPTIONS = [
  'PENDING',
  'APPROVED',
  'BLOCKED'
]

const TASK_UPDATE_TYPE_OPTIONS = [
  'NOTE',
  'STATUS',
  'BLOCKER',
  'HANDOFF',
  'READINESS'
]

function normalizeReferenceValue(value) {
  return String(value || '').trim().toUpperCase().replace(/[ -]/g, '_')
}

module.exports = {
  BOOKING_STATUS_OPTIONS,
  OPERATIONAL_ROLE_OPTIONS,
  TURNAROUND_OPERATION_STATUS_OPTIONS,
  TURNAROUND_TASK_STATUS_OPTIONS,
  TURNAROUND_DEPENDENCY_STATUS_OPTIONS,
  TURNAROUND_HANDOFF_STATUS_OPTIONS,
  TURNAROUND_ESCALATION_SEVERITY_OPTIONS,
  TURNAROUND_ESCALATION_STATUS_OPTIONS,
  TURNAROUND_SIGNOFF_STATUS_OPTIONS,
  TASK_UPDATE_TYPE_OPTIONS,
  normalizeReferenceValue
}
