const AI_PROGRAM_PHASES = Object.freeze([
  { phase: 1, name: 'AI foundation', status: 'COMPLETE' },
  { phase: 2, name: 'Turnaround briefing', status: 'COMPLETE' },
  { phase: 3, name: 'Evaluation harness', status: 'COMPLETE' },
  { phase: 4, name: 'AI Quality Console', status: 'COMPLETE' },
  { phase: 5, name: 'Adversarial and resilience testing', status: 'COMPLETE' },
  { phase: 6, name: 'CI integration', status: 'IN_PROGRESS' }
])

function getAiProgramStatus() {
  return {
    program: 'Cruise Fleet Operations AI Quality Program',
    currentPhase: 6,
    completedPhases: 5,
    currentPhasePercentComplete: 25,
    phases: AI_PROGRAM_PHASES.map(phase => ({ ...phase })),
    phaseOneCapabilities: {
      providerAbstraction: true,
      deterministicTestProvider: true,
      structuredContracts: true,
      promptVersioning: true,
      evidenceGroundingValidation: true,
      roleAuthorizationBoundary: true,
      auditMetadata: true,
      persistentAuditEvents: true,
      timeoutEnforcement: true,
      transientRetryPolicy: true,
      validatedRuntimeConfiguration: true,
      productionModelProvider: true,
      providerCredentialValidation: true,
      strictStructuredOutputTranslation: true,
      normalizedUsageTelemetry: true,
      configurableCostEstimation: true,
      correlatedTelemetryLogging: true,
      productionConfigurationDocumentation: true,
      foundationArchitectureAudit: true,
      deploymentReadinessAssessment: true,
      completionAudit: true,
      phaseOneComplete: true,
      contextSizeLimit: true,
      userInterface: false
    },
    phaseTwoCapabilities: {
      operationScopedEvidenceLoading: true,
      taskEvidenceMapping: true,
      dependencyEvidenceMapping: true,
      handoffEvidenceMapping: true,
      staffingEvidenceMapping: true,
      signoffEvidenceMapping: true,
      escalationEvidenceMapping: true,
      riskPrioritizedEvidenceSelection: true,
      tenantScopedAuthorization: true,
      operationBriefingApi: true,
      briefingWorkspace: true,
      briefingHistory: true,
      reviewerFeedback: true,
      generationRegenerationUx: true,
      evidenceSummaryDisplay: true,
      historyReviewDisplay: true,
      responsiveBriefingWorkspace: true,
      browserWorkflowCoverage: true,
      providerDisabledUx: true,
      phaseTwoCompletionAudit: true,
      phaseTwoComplete: true
    },
    phaseThreeCapabilities: {
      reusableEvaluationCases: true,
      weightedScoringContract: true,
      deterministicBriefingEvaluator: true,
      evaluationSuiteRunner: true,
      diagnosticResults: true,
      architectureAudit: true,
      persistentRunStorage: true,
      baselineComparison: true,
      evaluationApi: true,
      expandedGoldenDataset: true,
      providerPromptMatrix: true,
      configurableReleasePolicy: true,
      releaseGateDecision: true,
      qualityConsoleIntegration: true,
      completionAudit: true,
      phaseThreeComplete: true
    },
    phaseFourCapabilities: {
      releaseReadinessSummary: true,
      evaluationHistoryTable: true,
      trendAnalysis: true,
      providerModelPromptMetadata: true,
      failedCaseDrilldown: true,
      recurringFailureSummary: true,
      baselineSelection: true,
      runComparison: true,
      releasePolicyControls: true,
      historyFiltering: true,
      historySorting: true,
      phaseFourComplete: true
    },
    phaseFiveCapabilities: {
      adversarialScenarioContract: true,
      reusableScenarioCatalog: true,
      deterministicScenarioExecution: true,
      resilienceScoring: true,
      diagnosticFindings: true,
      adversarialSuiteRunner: true,
      architectureAudit: true,
      operationalEvidenceAttacks: true,
      promptInjectionCoverage: true,
      authorizationAttackCoverage: true,
      tenantIsolationAttackCoverage: true,
      providerFailureCoverage: true,
      malformedOutputCoverage: true,
      contextOverflowCoverage: true,
      providerDisabledCoverage: true,
      cancellationCoverage: true,
      qualityConsoleIntegration: true,
      browserWorkflowCoverage: true,
      completionAudit: true,
      phaseFiveComplete: true
    },
    phaseSixCapabilities: {
      ciQualityGate: true,
      phaseAuditExecution: true,
      targetedAiRegressionExecution: true,
      machineReadableEvidence: true,
      alwaysPublishEvidence: true,
      jobSummaryReporting: true,
      releaseBlockingPolicy: false,
      historicalEvidenceComparison: false,
      qualityConsoleEvidenceIngestion: false,
      completionAudit: false,
      phaseSixComplete: false
    }
  }
}

module.exports = { AI_PROGRAM_PHASES, getAiProgramStatus }
