import {
  OperationsReadinessWorkspace,
  OperationsStaffingWorkspace
} from './OperationsStaffingReadinessWorkspaces.jsx'
import { OperationsTaskFlowWorkspaces } from './OperationsTaskFlowWorkspaces.jsx'
import { OperationsCommandOverviewCompatibility } from './OperationsCommandOverviewCompatibility.jsx'

export function OperationsWorkspaceRouter(props) {
  const {
    activeOperationsWorkspace,
    creatingEscalationId,
    creatingTaskId,
    creatingTaskUpdateId,
    deletingTaskId,
    dependencyWorkspaceSummary,
    error,
    escalationWorkspaceSummary,
    getEscalationCreateDraft,
    getEscalationUpdateDraft,
    getHandoffDraft,
    getOperationCommandDraft,
    getSignoffDraft,
    getStaffingDraft,
    getTaskCreateDraft,
    getTaskDetailDraft,
    getTaskUpdateDraft,
    handoffWorkspaceSummary,
    isLoading,
    mutationError,
    mutationStatus,
    onCreateEscalation,
    onCreateTask,
    onCreateTaskUpdate,
    onDeleteTask,
    onRetry,
    onUpdateEscalation,
    onUpdateHandoff,
    onUpdateOperationCommand,
    onUpdateSignoff,
    onUpdateStaffing,
    onUpdateTaskDetails,
    onUpdateTaskStatus,
    readinessOperations,
    readinessWorkspaceSummary,
    removeTask,
    roleView,
    saveEscalationCreate,
    saveEscalationUpdate,
    saveHandoffUpdate,
    saveOperationCommand,
    saveSignoff,
    saveStaffing,
    saveTaskCreate,
    saveTaskDetails,
    saveTaskUpdate,
    selectedDependency,
    selectedDependencyKey,
    selectedEscalation,
    selectedEscalationKey,
    selectedHandoff,
    selectedHandoffKey,
    selectedOperation,
    selectedOperationDependencies,
    selectedOperationEscalations,
    selectedOperationHandoffs,
    selectedOperationSignoffs,
    selectedOperationStaffing,
    selectedOperationTasks,
    selectedReadinessKey,
    selectedReadinessSignoff,
    selectedStaffing,
    selectedStaffingKey,
    selectedTaskKey,
    setSelectedDependencyId,
    setSelectedEscalationId,
    setSelectedHandoffId,
    setSelectedReadinessRole,
    setSelectedStaffingRole,
    setSelectedTaskId,
    staffingWorkspaceSummary,
    taskWorkspaceSummary,
    updateEscalationCreateDraft,
    updateEscalationDraft,
    updateHandoffDraft,
    updateOperationCommandDraft,
    updateSignoffDraft,
    updateStaffingDraft,
    updateStatus,
    updateTaskCreateDraft,
    updateTaskDetailDraft,
    updateTaskUpdateDraft,
    updatingEscalationId,
    updatingHandoffId,
    updatingOperationId,
    updatingSignoffKey,
    updatingStaffingKey,
    updatingTaskDetailsId,
    updatingTaskId,
    visibleReadinessOperations,
  } = props

  return (
    <>
            {mutationStatus && <p className="status-card compact ce-command-card" data-testid="react-operational-mutation-status">{mutationStatus}</p>}
            {mutationError && <p className="status-card compact error ce-feedback-message ce-editor-card" data-testid="react-operational-mutation-error">{mutationError}</p>}
      
            {isLoading ? (
              <p className="status-card compact ce-command-card" data-testid="react-operational-loading-state">Loading turnaround operations from the database...</p>
            ) : error ? (
              <div className="status-card compact ce-command-card" data-testid="react-operational-error-state">
                <p>{error}</p>
                <button type="button" className="secondary-action-button ce-button-secondary" onClick={onRetry}>Retry turnaround data</button>
              </div>
            ) : readinessOperations.length === 0 ? (
              <p className="status-card compact ce-command-card" data-testid="react-operational-empty-state">No turnaround operation records are available yet.</p>
            ) : activeOperationsWorkspace === 'readiness' && selectedOperation ? (
              <OperationsReadinessWorkspace
                selectedOperation={selectedOperation}
                readinessWorkspaceSummary={readinessWorkspaceSummary}
                selectedOperationSignoffs={selectedOperationSignoffs}
                selectedReadinessKey={selectedReadinessKey}
                setSelectedReadinessRole={setSelectedReadinessRole}
                selectedReadinessSignoff={selectedReadinessSignoff}
                getSignoffDraft={getSignoffDraft}
                updateSignoffDraft={updateSignoffDraft}
                saveSignoff={saveSignoff}
                updatingSignoffKey={updatingSignoffKey}
                onUpdateSignoff={onUpdateSignoff}
              />
            ) : activeOperationsWorkspace === 'staffing' && selectedOperation ? (
              <OperationsStaffingWorkspace
                selectedOperation={selectedOperation}
                selectedOperationStaffing={selectedOperationStaffing}
                staffingWorkspaceSummary={staffingWorkspaceSummary}
                selectedStaffingKey={selectedStaffingKey}
                setSelectedStaffingRole={setSelectedStaffingRole}
                selectedStaffing={selectedStaffing}
                getStaffingDraft={getStaffingDraft}
                updateStaffingDraft={updateStaffingDraft}
                saveStaffing={saveStaffing}
                updatingStaffingKey={updatingStaffingKey}
                onUpdateStaffing={onUpdateStaffing}
              />
            ) : ['dependencies', 'escalations', 'handoffs', 'tasks'].includes(activeOperationsWorkspace) && selectedOperation ? (
              <OperationsTaskFlowWorkspaces
                activeOperationsWorkspace={activeOperationsWorkspace}
                selectedOperation={selectedOperation}
                selectedOperationDependencies={selectedOperationDependencies}
                dependencyWorkspaceSummary={dependencyWorkspaceSummary}
                selectedDependencyKey={selectedDependencyKey}
                setSelectedDependencyId={setSelectedDependencyId}
                selectedDependency={selectedDependency}
                selectedOperationEscalations={selectedOperationEscalations}
                escalationWorkspaceSummary={escalationWorkspaceSummary}
                selectedEscalationKey={selectedEscalationKey}
                setSelectedEscalationId={setSelectedEscalationId}
                selectedEscalation={selectedEscalation}
                onCreateEscalation={onCreateEscalation}
                getEscalationCreateDraft={getEscalationCreateDraft}
                updateEscalationCreateDraft={updateEscalationCreateDraft}
                saveEscalationCreate={saveEscalationCreate}
                creatingEscalationId={creatingEscalationId}
                getEscalationUpdateDraft={getEscalationUpdateDraft}
                updateEscalationDraft={updateEscalationDraft}
                saveEscalationUpdate={saveEscalationUpdate}
                updatingEscalationId={updatingEscalationId}
                onUpdateEscalation={onUpdateEscalation}
                selectedOperationHandoffs={selectedOperationHandoffs}
                handoffWorkspaceSummary={handoffWorkspaceSummary}
                selectedHandoffKey={selectedHandoffKey}
                setSelectedHandoffId={setSelectedHandoffId}
                selectedHandoff={selectedHandoff}
                onUpdateHandoff={onUpdateHandoff}
                getHandoffDraft={getHandoffDraft}
                updateHandoffDraft={updateHandoffDraft}
                saveHandoffUpdate={saveHandoffUpdate}
                updatingHandoffId={updatingHandoffId}
                selectedOperationTasks={selectedOperationTasks}
                taskWorkspaceSummary={taskWorkspaceSummary}
                selectedTaskKey={selectedTaskKey}
                setSelectedTaskId={setSelectedTaskId}
                onCreateTask={onCreateTask}
                getTaskCreateDraft={getTaskCreateDraft}
                updateTaskCreateDraft={updateTaskCreateDraft}
                saveTaskCreate={saveTaskCreate}
                creatingTaskId={creatingTaskId}
                getTaskUpdateDraft={getTaskUpdateDraft}
                updateTaskUpdateDraft={updateTaskUpdateDraft}
                saveTaskUpdate={saveTaskUpdate}
                creatingTaskUpdateId={creatingTaskUpdateId}
                onCreateTaskUpdate={onCreateTaskUpdate}
                onUpdateTaskDetails={onUpdateTaskDetails}
                getTaskDetailDraft={getTaskDetailDraft}
                updateTaskDetailDraft={updateTaskDetailDraft}
                saveTaskDetails={saveTaskDetails}
                updatingTaskDetailsId={updatingTaskDetailsId}
                onUpdateTaskStatus={onUpdateTaskStatus}
                updatingTaskId={updatingTaskId}
                updateStatus={updateStatus}
                onDeleteTask={onDeleteTask}
                deletingTaskId={deletingTaskId}
                removeTask={removeTask}
              />
            ) : (
              <OperationsCommandOverviewCompatibility
                creatingEscalationId={creatingEscalationId}
                creatingTaskId={creatingTaskId}
                creatingTaskUpdateId={creatingTaskUpdateId}
                deletingTaskId={deletingTaskId}
                getEscalationCreateDraft={getEscalationCreateDraft}
                getEscalationUpdateDraft={getEscalationUpdateDraft}
                getHandoffDraft={getHandoffDraft}
                getOperationCommandDraft={getOperationCommandDraft}
                getSignoffDraft={getSignoffDraft}
                getStaffingDraft={getStaffingDraft}
                getTaskCreateDraft={getTaskCreateDraft}
                getTaskDetailDraft={getTaskDetailDraft}
                getTaskUpdateDraft={getTaskUpdateDraft}
                onCreateEscalation={onCreateEscalation}
                onCreateTask={onCreateTask}
                onCreateTaskUpdate={onCreateTaskUpdate}
                onDeleteTask={onDeleteTask}
                onUpdateEscalation={onUpdateEscalation}
                onUpdateHandoff={onUpdateHandoff}
                onUpdateOperationCommand={onUpdateOperationCommand}
                onUpdateSignoff={onUpdateSignoff}
                onUpdateStaffing={onUpdateStaffing}
                onUpdateTaskDetails={onUpdateTaskDetails}
                onUpdateTaskStatus={onUpdateTaskStatus}
                removeTask={removeTask}
                roleView={roleView}
                saveEscalationCreate={saveEscalationCreate}
                saveEscalationUpdate={saveEscalationUpdate}
                saveHandoffUpdate={saveHandoffUpdate}
                saveOperationCommand={saveOperationCommand}
                saveSignoff={saveSignoff}
                saveStaffing={saveStaffing}
                saveTaskCreate={saveTaskCreate}
                saveTaskDetails={saveTaskDetails}
                saveTaskUpdate={saveTaskUpdate}
                updateEscalationCreateDraft={updateEscalationCreateDraft}
                updateEscalationDraft={updateEscalationDraft}
                updateHandoffDraft={updateHandoffDraft}
                updateOperationCommandDraft={updateOperationCommandDraft}
                updateSignoffDraft={updateSignoffDraft}
                updateStaffingDraft={updateStaffingDraft}
                updateStatus={updateStatus}
                updateTaskCreateDraft={updateTaskCreateDraft}
                updateTaskDetailDraft={updateTaskDetailDraft}
                updateTaskUpdateDraft={updateTaskUpdateDraft}
                updatingEscalationId={updatingEscalationId}
                updatingHandoffId={updatingHandoffId}
                updatingOperationId={updatingOperationId}
                updatingSignoffKey={updatingSignoffKey}
                updatingStaffingKey={updatingStaffingKey}
                updatingTaskDetailsId={updatingTaskDetailsId}
                updatingTaskId={updatingTaskId}
                visibleReadinessOperations={visibleReadinessOperations}
              />
            )}
    </>
  )
}
