-- Removes cruise lines accidentally left behind by integration/Cypress/manual test runs.
-- Safe target: only names generated by the test prefix "Created Cruise Line".

DELETE FROM ships
WHERE cruise_line_id IN (
  SELECT id
  FROM cruise_lines
  WHERE name LIKE 'Created Cruise Line%'
);

DELETE FROM cruise_lines
WHERE name LIKE 'Created Cruise Line%';
